//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_PeriodCallBackManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.PeriodCallBackManager), typeof(SingletonManager<LuaFramework.PeriodCallBackManager>));
		L.RegFunction("CallBack", CallBack);
		L.RegFunction("AddCallBack", AddCallBack);
		L.RegFunction("RemoveCallBack", RemoveCallBack);
		L.RegFunction("RemoveAll", RemoveAll);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("GetObjCallBack", GetObjCallBack);
		L.RegFunction("GetObjAllCallBack", GetObjAllCallBack);
		L.RegFunction("New", _CreateLuaFramework_PeriodCallBackManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("PeriodDic", get_PeriodDic, set_PeriodDic);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaFramework_PeriodCallBackManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaFramework.PeriodCallBackManager obj = new LuaFramework.PeriodCallBackManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaFramework.PeriodCallBackManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallBack(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			LuaFramework.PeriodCallBackManager.CallBackEnum arg0 = (LuaFramework.PeriodCallBackManager.CallBackEnum)ToLua.CheckObject(L, 2, typeof(LuaFramework.PeriodCallBackManager.CallBackEnum));
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			object[] arg2 = ToLua.ToParamsObject(L, 4, count - 3);
			obj.CallBack(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			LuaFramework.PeriodCallBackManager.CallBackEnum arg0 = (LuaFramework.PeriodCallBackManager.CallBackEnum)ToLua.CheckObject(L, 2, typeof(LuaFramework.PeriodCallBackManager.CallBackEnum));
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddCallBack(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			LuaFramework.PeriodCallBackManager.CallBackEnum arg0 = (LuaFramework.PeriodCallBackManager.CallBackEnum)ToLua.CheckObject(L, 2, typeof(LuaFramework.PeriodCallBackManager.CallBackEnum));
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			obj.RemoveCallBack(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			obj.RemoveAll();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Destroy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			LuaFramework.PeriodCallBackManager.CallBackEnum arg0 = (LuaFramework.PeriodCallBackManager.CallBackEnum)ToLua.CheckObject(L, 2, typeof(LuaFramework.PeriodCallBackManager.CallBackEnum));
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			LuaInterface.LuaFunction o = obj.GetObjCallBack(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjAllCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.PeriodCallBackManager obj = (LuaFramework.PeriodCallBackManager)ToLua.CheckObject<LuaFramework.PeriodCallBackManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			System.Collections.Generic.Dictionary<string,LuaInterface.LuaFunction> o = obj.GetObjAllCallBack(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PeriodDic(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, LuaFramework.PeriodCallBackManager.PeriodDic);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PeriodDic(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<LuaFramework.PeriodCallBackManager.CallBackEnum,System.Collections.Generic.Dictionary<string,LuaInterface.LuaFunction>> arg0 = (System.Collections.Generic.Dictionary<LuaFramework.PeriodCallBackManager.CallBackEnum,System.Collections.Generic.Dictionary<string,LuaInterface.LuaFunction>>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<LuaFramework.PeriodCallBackManager.CallBackEnum,System.Collections.Generic.Dictionary<string,LuaInterface.LuaFunction>>));
			LuaFramework.PeriodCallBackManager.PeriodDic = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

