//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_PeriodCallBackManager_CallBackEnumWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaFramework.PeriodCallBackManager.CallBackEnum));
		L.RegVar("Awake", get_Awake, null);
		L.RegVar("Start", get_Start, null);
		L.RegVar("TriggerEnter", get_TriggerEnter, null);
		L.RegVar("TriggerExit", get_TriggerExit, null);
		L.RegVar("CollisionEnter", get_CollisionEnter, null);
		L.RegVar("CollisionExit", get_CollisionExit, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaFramework.PeriodCallBackManager.CallBackEnum>.Check = CheckType;
		StackTraits<LuaFramework.PeriodCallBackManager.CallBackEnum>.Push = Push;
	}

	static void Push(IntPtr L, LuaFramework.PeriodCallBackManager.CallBackEnum arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaFramework.PeriodCallBackManager.CallBackEnum), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Awake(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.Awake);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Start(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.Start);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TriggerEnter(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.TriggerEnter);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TriggerExit(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.TriggerExit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CollisionEnter(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.CollisionEnter);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CollisionExit(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.PeriodCallBackManager.CallBackEnum.CollisionExit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaFramework.PeriodCallBackManager.CallBackEnum o = (LuaFramework.PeriodCallBackManager.CallBackEnum)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

