//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingletonManager_LuaFramework_PeriodCallBackManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingletonManager<LuaFramework.PeriodCallBackManager>), typeof(System.Object), "SingletonManager_LuaFramework_PeriodCallBackManager");
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("New", _CreateSingletonManager_LuaFramework_PeriodCallBackManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingletonManager_LuaFramework_PeriodCallBackManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SingletonManager<LuaFramework.PeriodCallBackManager> obj = new SingletonManager<LuaFramework.PeriodCallBackManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SingletonManager<LuaFramework.PeriodCallBackManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LuaFramework.PeriodCallBackManager o = SingletonManager<LuaFramework.PeriodCallBackManager>.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

